#!/usr/bin/env python3
"""Replace Chinese comments with English in terminal.ts"""
import os
script_dir = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(script_dir)
path = os.path.join(root, "packages/repterm/src/terminal/terminal.ts")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
replacements = [
    ("// ★ 原子查询：一次 tmux 调用同时获取 history_size 和 cursor_y", "// Atomic: single tmux call for history_size and cursor_y"),
    ("// 创建临时 tmux session", "// Create temp tmux session"),
    ("await this.sleep(1000); // 等待 shell 启动", "await this.sleep(1000); // Wait for shell to start"),
    ("// ★ 检测提示符 pattern（在发送命令前捕获干净的提示符）", "// Capture prompt pattern before sending command"),
    ("// 发送测试命令（用于检测提示符行数）", "// Send test command to detect prompt line count"),
    ("await this.sleep(1000); // 等待命令执行完成", "await this.sleep(1000); // Wait for command to finish"),
    ("// 获取当前 cursorY", "// Get current cursorY"),
    ("// 捕获屏幕内容", "// Capture screen content"),
    ("markerLine = i;  // 不 break，继续找下一个，最终得到最后一次出现的位置", "markerLine = i;  // Keep going to get last occurrence"),
    ("// 提示符行数 = cursorY - markerLine", "// promptLineCount = cursorY - markerLine"),
    ("// 关闭临时 session", "// Kill temp session"),
    ("// 检测失败时保持默认值", "// On failure keep defaults"),
    ("// 尝试清理临时 session", "// Try to kill temp session"),
    ("// 常见提示符字符", "// Common prompt chars"),
    ("// 查找提示符字符的位置（选最后出现的）", "// Find prompt char position (last occurrence)"),
    ("// 分析提示符后的内容", "// Analyze content after prompt"),
    ("// 转义特殊正则字符", "// Escape regex special chars"),
    ("// 右侧提示符布局：提示符后有多个空格再有内容", "// Right-side prompt: spaces then content"),
    ("// 传统布局：提示符在行尾", "// Traditional: prompt at EOL"),
    ("// 速度为 0 时直接写入", "// speed 0: write directly"),
    ("let momentum = 0; // 打字动量，模拟熟练度", "let momentum = 0; // Typing momentum"),
    ("// 变速模式：模拟真实打字的加速和减速", "// Variable speed: accelerate/decelerate"),
    ("// 单词边界：重置动量，稍长停顿", "// Word boundary: reset momentum, longer pause"),
    ("// 连续打字：逐渐加速", "// Continuous typing: speed up"),
    ("// 标点符号后额外停顿", "// Extra pause after punctuation"),
    ("// 原有模式：固定速度 ± 30%", "// Legacy: fixed speed +/- 30%"),
    ("// 引号特殊处理", "// Special handling for quotes"),
    ("// 显示注释形式的标题", "// Show title as comment"),
    ("await this.sleep(500); // 让标题显示片刻", "await this.sleep(500); // Brief display"),
    ("// 多行命令：使用 Bracketed Paste Mode 避免续行提示符", "// Multiline: Bracketed Paste to avoid continuation prompt"),
    ("// 禁用打字效果时：快速写入", "// When typing disabled: write fast"),
    ("// 正常命令：人工打字效果（无论长度）", "// Normal command: human typing"),
    ("// Bracketed Paste Mode 转义序列", "// Bracketed Paste escape sequences"),
    ("// 包裹命令内容（不包含最后的回车，回车在粘贴结束后单独发送）", "// Wrap command (no final newline; send after paste)"),
    ("// 使用 tmux send-keys -l 发送字面内容（包含转义序列）", "// tmux send-keys -l for literal content"),
    ("// 等待 shell 处理", "// Wait for shell to process"),
    ("// 发送回车执行命令", "// Send Enter to run command"),
    ("// 用于非录制、非交互模式的 Bun.spawn 进程", "// Bun.spawn for non-recording, non-interactive"),
    ("// 用于非录制交互模式的输出起始位置", "// Output start for non-recording interactive"),
    ("// 包含 ptyOnly 模式", "// Include ptyOnly"),
    ("// 录制模式或交互式：使用 PTY", "// Recording or interactive: use PTY"),
    ("// 非录制交互模式：记录当前输出长度", "// Non-recording interactive: record output length"),
    ("// 合并选项优先级：RunOptions > StepOptions > 默认值", "// Option priority: RunOptions > StepOptions > default"),
    ("// 非录制、非交互：使用 Bun.spawn", "// Non-recording, non-interactive: Bun.spawn"),
    ("// PTY 模式：等待输出稳定", "// PTY: wait for output to stabilize"),
    ("// 录制模式：使用发送 Enter 前记录的状态计算输出范围", "// Recording: use state before Enter for output range"),
    ("// 去除尾部空白行", "// Trim trailing blank lines"),
    ("// 非录制交互模式：使用 session buffer", "// Non-recording interactive: use session buffer"),
    ("code: -1, // PTY 模式无法可靠获取退出码，设为 -1 表示不可用", "code: -1, // PTY: exitCode unreliable"),
    ("// Bun.spawn 模式：等待进程结束", "// Bun.spawn: wait for process exit"),
    ("// 将输出存储到终端，支持 expect(terminal).toContainText() 断言", "// Store output for expect(terminal).toContainText()"),
    ("   * 是否使用 PTY 模式（录制或 pty-only）\n   * PTY 模式支持交互式命令，但打字效果仅在 recording 模式下启用", "   * Whether PTY mode (recording or pty-only). Typing effect only in recording."),
    ("   * 使用单次 tmux 查询原子获取 history_size 和 cursor_y，避免竞态条件", "   * Single tmux query for history_size and cursor_y to avoid race."),
    ("   * 在录制开始前检测提示符相关信息\n   * - 提示符占用的行数\n   * - 提示符匹配 pattern\n   * 通过创建临时 tmux session 来测量，检测过程不会出现在录制中", "   * Detect prompt before recording (line count, pattern) via temp tmux session."),
    ("      // 找到测试字符串的行（找最后一次出现，即 echo 的输出，而非命令回显）", "      // Find test string line (last occurrence = echo output)"),
    ("   * 分析提示符行，生成匹配正则", "   * Analyze prompt line and build match regex"),
    ("   * 获取检测到的提示符行数", "   * Get detected prompt line count"),
    ("   * 获取检测到的提示符匹配 pattern", "   * Get detected prompt pattern"),
    ("   * @param text - 要打字的文本\n   * @param speed - 每字符延迟 (ms)，默认 80ms\n   * @param variableSpeed - 是否使用变速模式（更自然）", "   * @param text - Text to type\n   * @param speed - ms per char, default 80\n   * @param variableSpeed - Variable speed for natural typing"),
    ("   * 在录制中显示步骤标题", "   * Show step title in recording"),
    ("    // 检测行中任意位置的提示符（支持右侧提示符布局）\n    // 提示符后面通常跟着空格（输入区域）\n    // 使用检测到的 pattern，或默认 pattern", "    // Detect prompt (right-side layout); use detected or default pattern"),
    ("    // ★ 命令前暂停", "    // Pause before command"),
    ("    // ★ 显示步骤标题（每个 step 只显示一次）", "    // Show step title (once per step)"),
    ("    // ★ 记录命令行数（直接从命令内容计算，最可靠）", "    // Record command line count from content"),
    ("        // ★ 在发送 Enter 之前记录状态", "        // Record state before sending Enter"),
    ("   * 使用 Bracketed Paste Mode 粘贴多行命令\n   * 避免 shell 显示续行提示符（如 quote>、pipe heredoc>）\n   * Bracketed Paste Mode 使用转义序列包裹粘贴内容：\n   * - \\x1b[200~ 标记粘贴开始\n   * - \\x1b[201~ 标记粘贴结束\n   * Shell 会将整个内容作为单个输入块处理，不显示续行提示符", "   * Bracketed Paste for multiline; \\x1b[200~...\\x1b[201~ so no continuation prompt."),
    ("    // ★ 在发送 Enter 之前记录状态（用于输出范围捕获）", "    // Record state before Enter (for output range)"),
    (" * PTYProcess 实现类\n * 实现 PromiseLike 接口，支持 await 和控制器两种用法\n * \n * 执行模式：\n * - 非录制、非交互：使用 Bun.spawn，stdout/stderr 分离，exitCode 精确\n * - 录制或交互：使用 PTY，支持 expect/send，但 exitCode 不可靠（返回 -1）", " * PTYProcess impl. PromiseLike: await or controller. Non-recording: Bun.spawn, exact exitCode; recording/interactive: PTY, exitCode -1."),
    ("  // ===== PromiseLike 实现 =====\n\n  /**\n   * 实现 PromiseLike.then()\n   * await proc 时自动调用此方法", "  // ===== PromiseLike =====\n\n  /** then(): called when awaiting proc"),
    ("   * 实现 catch 方法（便捷方法）", "   * catch (convenience)"),
    ("   * 实现 finally 方法（便捷方法）", "   * finally (convenience)"),
    ("  // ===== 内部方法 =====\n\n  /**\n   * 判断是否使用 PTY 模式（录制、ptyOnly 或交互）\n   * silent 模式强制使用 Bun.spawn 获取干净输出", "  // ===== Internal =====\n\n  /** PTY when recording/ptyOnly/interactive; silent forces Bun.spawn for clean output"),
    ("   * 延时辅助方法", "   * Sleep helper"),
    ("   * 原子获取 pane 状态（history_size 和 cursor_y）\n   * 使用单次 tmux 调用避免竞态条件", "   * Get pane state atomically (single tmux call)"),
    ("   * 捕获 pane 指定范围的输出\n   * @param startLine 起始行（负数=历史，正数=可见区域，'-'=历史开头）\n   * @param endLine 结束行（'-'=当前位置）", "   * Capture pane output range. startLine/endLine: negative=history, '-'=start/current"),
    ("   * 去除 ANSI 转义序列", "   * Strip ANSI escapes"),
    ("   * 启动命令\n   * - PTY 模式：通过 terminal.executeInPty 执行\n   * - Bun.spawn 模式：直接启动子进程", "   * Start: PTY via executeInPty or Bun.spawn"),
    ("      // executeInPty 内部会在发送 Enter 前记录状态\n      // ★ 从当前 step 上下文获取录制选项", "      // executeInPty records state before Enter; get options from step"),
    ("  // ===== 交互式控制方法 =====\n\n  /**\n   * Wait for specified text to appear\n   * 仅在交互模式或录制模式下可用", "  // ===== Interactive =====\n\n  /** Wait for text. Only in interactive or recording."),
    ("   * Send input to the process (with newline)\n   * 仅在交互模式或录制模式下可用", "   * Send input (with newline). Only in interactive or recording."),
    ("   * Send raw input to the process (without newline)\n   * 仅在交互模式或录制模式下可用", "   * Send raw input. Only in interactive or recording."),
    ("   * 启动命令执行，等待输入完成（不等待命令执行完成）\n   * 用于 watch 等长时间运行的命令", "   * Start command, wait for input only (e.g. watch)."),
    ("      // ★ 命令后暂停（录制模式）", "      // Pause after command (recording)"),
    ("        // ★ 使用 tmux send-keys 直接发送到指定窗格\n        // 不依赖当前活动窗格状态", "        // tmux send-keys to target pane"),
]
for old, new_ in replacements:
    if old in content:
        content = content.replace(old, new_)
        print("Replaced:", old[:45])
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done.")
